swagger: "2.0"
info:
  title: "Greenlab API"
  version: "1"
schemes:
  - "http"
definitions:
  HealthCheckResponse:
    type: "object"
    properties:
      message:
        type: "string"
  UserRequest:
    type: "object"
    properties:
      name:
        type: "string"
      phone_number:
        type: "string"
      city:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      phone_number:
        type: "string"
      city:
        type: "string"
      quiz_results:
        type: "array"
        items:
          $ref: "#definitions/QuizResult"

  UsersList:
      type: "array"
      items:
        $ref: "#definitions/User"
  Category:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
  CategoriesList:
    type: "array"
    items:
      $ref: "#definitions/Category"
  Question:
    type: "object"
    properties:
        id:
          type: "string"
        value:
          type: "string"
  QuestionsList:
    type: "array"
    items:
      $ref: "#definitions/Question"
  QuizResult:
    type: "object"
    properties:
      quiz_result_items:
        type: "array"
        items:
          $ref: "#definitions/QuizResultItem"
  QuizResultItem:
    type: "object"
    properties:
      category:
        $ref: "#definitions/Category"
      percentage:
        type: "number"
  FinishQuizRequest:
    type: "object"
    properties:
      user_id:
        type: "string"
      result:
        type: "array"
        items:
          type: "object"
          properties:
            question_id:
              type: "string"
            answer:
              type: "string"
  Stats:
    type: "object"
    properties:
      total_users:
        type: "integer"

  Error:
    type: "object"