swagger: "2.0"
info:
  title: "Greenlab API"
  version: "1"
schemes:
  - "http"
definitions:
  HealthCheckResponse:
    type: "object"
    properties:
      message:
        type: "string"
  UserRequest:
    type: "object"
    properties:
      name:
        type: "string"
      phone_number:
        type: "string"
      city:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      phone_number:
        type: "string"
      city:
        type: "string"
  UsersList:
      type: "array"
      items:
        $ref: "#definitions/User"
  Error:
    type: "object"